### ISSUE TITLE
TFJS model checkpoint

### ISSUE THREAD

**Issue by ceyxasm** [HSE-asavchenko/HSE_FaceRec_tf#5]
Dear team, I want to be able to use your model in node environment and I was wondering if you have your weights required for TFJS format.

**Comment by mingrongchen** [comment]
我已收到您的邮件，谢谢！

**Comment by av-savchenko** [comment]
Hello! Thanks for your question. I do not have an experience with TFJS, so I have not provided special models. However, you could try to use existing tools that convert keras (h5/hdf5) models to TFJS format, e.g., [official link](https://www.tensorflow.org/js/tutorials/conversion/import_keras)

**Comment by ceyxasm** [comment]
Hello team, I was able to convert the model to TFJS and verify its sanity. However I am not facing another issue and I have raised the same here #6
Close this

**Comment by mingrongchen** [comment]
我已收到您的邮件，谢谢！
